---

- name: Install /etc/default/docker
  sudo: true
  template: >
    src=docker.default.j2
    dest=/etc/default/docker
    owner=root
    group=root
    mode=0644
  notify:
    - restart docker
  when: start_docker_service == True
