---

- hosts: vagrant_dockerswarm
  sudo: true
  remote_user: "{{ user }}"
  vars:
    consul_is_ui: true
    consul_is_server: true
    consul_datacenter: "test"
    consul_bootstrap: true
    consul_node_name: "vagrant"
    consul_bind_address: "{{ ansible_default_ipv4['address'] }}"
    nginx_remove_default: true
    swarm_discovery: consul
    swarm_discovery_string: 'consul://dockerswarm01/swarm'

  roles:
    - role: base
    - role: docker
    - role: docker_swarm
    - role: franklinkim.consul
